### ISSUE TITLE
Update Schema from enum to array of enum for PurposeofSequencing

### ISSUE THREAD

**Issue by sifavahora** [cancogen-virus-seq/metadata-schemas#26]
This change will allow us to have multiple tags for the property https://github.com/cancogen-virus-seq/portal/issues/188

**Comment by b-f-chan** [comment]
@edsu7 has a branch ready, but don't push this change to Dev until the Releases page issue has been resolved

**Comment by sifavahora** [comment]
Can be tested once corresponding Muse changes are in place.

**Comment by UmmulkiramR** [comment]
Temporarily reverted this change from dev to be able to test ticket #292 since #188 is still not on dev.

**Comment by UmmulkiramR** [comment]
Schema changes have been restored on dev
