### ISSUE TITLE
Update Schema from enum to array of enum for anatomical_Part

### ISSUE THREAD

**Issue by sifavahora** [cancogen-virus-seq/metadata-schemas#27]
This change will allow us to have multiple tags for the propertyhttps://github.com/cancogen-virus-seq/portal/issues/265

**Comment by sifavahora** [comment]
Can be tested once corresponding Muse changes are in place.

**Comment by UmmulkiramR** [comment]
Temporarily reverted this change from dev to be able to test ticket #292 since #188 is still not on dev.
