### ISSUE TITLE
Feature request for depth and breadth of coverage columns in the schema

### ISSUE THREAD

**Issue by nithujohn** [cancogen-virus-seq/metadata-schemas#30]
Hi @scottcain/ @sifavahora, I have a  request from one of the data providers who wants to leave the columns "depth of coverage" and "breadth of coverage" blank as they say it's not a real indicator to put null values. Currently I have to include either the values or Null values to the column or it  will result in schema error. Is that possible to modify these to columns and if so, how long it would take? thanks!

**Comment by leoraba** [comment]
@nithujohn the schema has been updated. thanks!

**Comment by nithujohn** [comment]
Thank you! @lindaxiang @leoraba
