### ISSUE TITLE
schema update

### ISSUE THREAD

**Issue by lindaxiang** [cancogen-virus-seq/metadata-schemas#4]
- [x] add 4 new fields
1. gene name
2. diagnostic pcr Ct value
3. sample collection date null reason
4. host age null reason

- [x] make sure the following fields are NOT required fields in schema as we are not going to expect them in the submitted TSV
1. sample collection date precision
2. NML submitted specimen type
3. Ns per 100 kbp
4. consensus genome length
5. geo_loc_name (city)
6. library ID
7. lineage/clade analysis software name
8. lineage/clade analysis software version
9. lineage/clade name
10. sequencing date
11. variant designation
12. variant evidence
13. variant evidence details

- [x] rename field `sequencing_protocol_name` to `sequencing_protocol`

- [x] update some CV terms in the schema to sync with [latest DH](https://github.com/Public-Health-Bioinformatics/DataHarmonizer/releases/tag/v0.13.28)

**Comment by lindaxiang** [comment]
Addressed by: https://github.com/cancogen-virus-seq/metadata-schemas/pull/5

**Comment by lindaxiang** [comment]
1. One new column `FASTA header name` need to be added.
- This field in the TSV will specify how the sample is labeled in FASTA.

2. Column `Isolate` 
- This field is reserved for GISAID virus names.  So samples don't meet GISAID quality threshold won't have a GISAID virus name
- It's possible the `Isolate` column to be `null`

**Comment by rosibaj** [comment]
@lindaxiang as discussed, we need one more update to remove teh `1` from the field names.  the added names should be like so: 
```
gene_name
diagnostic_pcr_ct_value
```

**Comment by lindaxiang** [comment]
Addressed by https://github.com/cancogen-virus-seq/metadata-schemas/pull/6

**Comment by rosibaj** [comment]
has been updated in prod
